version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    expose:
      - 5672
    ports:
      - 5672:5672
      - 15672:15672

  orig:
    build: ./orig
    container_name: orig
    depends_on:
      - rabbitmq

  imed:
    build: ./imed
    container_name: imed
    depends_on:
      - rabbitmq

  obse:
    build:
      context: ./
      dockerfile: ./obse/Dockerfile
    container_name: obse
    volumes:
      - ./data:/app/data
    depends_on:
      - rabbitmq

  httpserv:
    build:
      context: ./
      dockerfile: ./httpserv/Dockerfile
    container_name: httpserv
    ports:
      - 8080:80
    volumes:
      - ./data:/app/data